### ISSUE TITLE
Upstream SELinux policy

### ISSUE THREAD

**Issue by flihp** [intel/tpm2-abrmd#207]
Fedora systems required some SELinux fixes for the daemon to run: see #203. This policy works for fedora but it needs to be refactored and tested with the upstream SELinux refpol.

**Comment by martinezjavier** [comment]
@flihp I think this should be closed now that PR #299 has been merged (I forgot to mention Lukas to add a  Fixes: tag).

**Comment by flihp** [comment]
no worries @martinezjavier, thanks for the reminder
