### ISSUE TITLE
coveralls in PRs

### ISSUE THREAD

**Issue by flihp** [intel/tpm2-abrmd#272]
Due to the way we are setting up the travis-ci environment variables we only get code coverage metrics for the main branches in the repo and any PRs from branches in the repo. We need to figure out how to get coverage metrics for PRs too.

**Comment by flihp** [comment]
This turns out to be more difficult than it should be. Every example I've been able to find only collect metrics for PRs that originate from within the same git repo. People submitting PRs can hook their private forks up to their own coveralls space if they want need to. Won't fix for now.

**Comment by williamcroberts** [comment]
It's not more difficult than it should be, its about protecting sensitive env variables from untrusted PRs. Think, if anyone could do it, anyone can send you a PR and nab your coveralls repo token and then use your free quota for the month, or a myriad of other more nasty things.

**Comment by flihp** [comment]
I understand the threat and the possible negative consequences. I'm just expressing an opinion: collecting code coverage metrics for PRs shouldn't be difficult.
