### ISSUE TITLE
tss2-tcti-tabrmd_unit failing after upstream TCTI changes

### ISSUE THREAD

**Issue by flihp** [intel/tpm2-abrmd#281]
No clue what's causing this since it's only reproducible on travis-ci now. Will take some digging. Unfortunately the failure is in a file with ~30 unit tests and > 1000 LOC :frowning_face:

**Comment by flihp** [comment]
Failure is in function: tcti_tabrmd_init_success_test. Unfortunately this looks like the unit test is attempting to acquire a connection with the dbus system bus which should only work on systems with a system bus. Since the travis build has never had a system bus available I'm not sure how this worked in the first place.

Switching this over to use the session bus may be a good short term fix. Implementing a proper mock object, or maybe just mocking the function (not sure which) that makes the connection will be sufficient.

**Comment by flihp** [comment]
resolved in #283

**Comment by liuqun** [comment]
Hi @flihp !
tcti_tabrmd_init_success_test() also crash when I try to run "test/tss2-tcti-tabrmd_unit".
It reports:
> ERROR: failed to allocate dbus proxy object: Cannot autolaunch D-Bus without X11 $DISPLAY

see bug report:
https://github.com/intel/tpm2-abrmd/issues/293

**Comment by flihp** [comment]
Hey @liuqun. I replied to #293 with relevant data earlier today. All of the TCTI unit tests will produce the same problem and https://github.com/intel/tpm2-abrmd/issues/303 should cover the resolution.
