### ISSUE TITLE
test/tss2-tcti-tabrmd_unit will crash if "make check-TESTS" from a ssh terminal

### ISSUE THREAD

**Issue by liuqun** [intel/tpm2-abrmd#293]
ERROR: failed to allocate dbus proxy object: Cannot autolaunch D-Bus without X11 $DISPLAY

**This bug only happens on Raspberry Pi and only happens when loginto it from a ssh terminal**

./bootstrap && ./configure --enable-unit

make check
![](https://user-images.githubusercontent.com/64795/35084765-764c1cd0-fc60-11e7-99e5-969144b39131.png)

cat [test-suite.log](https://github.com/intel/tpm2-abrmd/files/1641899/test-suite.log)
```
====================================================
   tpm2-abrmd 1.2.0-87-g3631c7d: ./test-suite.log
====================================================

# TOTAL: 25
# PASS:  24
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test/tss2-tcti-tabrmd_unit
================================

[==========] Running 42 test(s).
[ RUN      ] tcti_tabrmd_init_size_test
[       OK ] tcti_tabrmd_init_size_test
[ RUN      ] tcti_tabrmd_init_success_return_value_test
[       OK ] tcti_tabrmd_init_success_return_value_test
[ RUN      ] tcti_tabrmd_init_allnull_is_bad_value_test
[       OK ] tcti_tabrmd_init_allnull_is_bad_value_test
[ RUN      ] tcti_tabrmd_init_success_test

** (process:32002): ERROR **: failed to allocate dbus proxy object: Cannot autolaunch D-Bus without X11 $DISPLAY
FAIL test/tss2-tcti-tabrmd_unit (exit status: 133)
```

```
pi@RaspberryPi:~/build3/abrmd$ git describe --tags --always --dirty
1.2.0-87-g3631c7d

pi@RaspberryPi:~/build3/abrmd$ git show
commit 3631c7d6033b96599c0824ba9be02fbaed124000
Merge: b47738b dafa52c
Author: Philip Tricca <philip.b.tricca@intel.com>
Date:   Wed Jan 17 15:43:30 2018 -0800

    Merge remote-tracking branch 'origin/1.x'
```

https://github.com/intel/tpm2-abrmd/blob/3631c7d6033b96599c0824ba9be02fbaed124000/test/tss2-tcti-tabrmd_unit.c#L240-L253

```
pi@RaspberryPi:~/build3/abrmd$ dbus-daemon --version
D-Bus Message Bus Daemon 1.10.6
Copyright (C) 2002, 2003 Red Hat, Inc., CodeFactory AB, and others
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by liuqun** [comment]
The previous PR https://github.com/intel/tpm2-abrmd/pull/283 suggests to use dbus session-bus.
But it doesn't work for me.

**Comment by flihp** [comment]
try running: `dbus-launch make check-TESTS`. Your ssh session doesn't have a dbus session bus running so you need to manually create one for `make check`. This is what we do for .travis.ci: https://github.com/intel/tpm2-abrmd/blob/master/.travis.yml#L88

**Comment by flihp** [comment]
closing, please re-open if necessary

**Comment by liuqun** [comment]
Thanks @flihp 
dbus-launch works for me

By the way, please consider adding an FAQ check-list to testsuit.log
It would be helpful when any Linux distro maintainers want to build tabrmd inside their package build systems, in case they desided to keep the unit tests enabled.

**Comment by flihp** [comment]
I agree that the unit test shouldn't access dbus (this is a bug). The integration tests all require access to some dbus instance though which is expected. Just created #303 to track the removal of the dbus call from the unit tests. Thanks!

**Comment by smcv** [comment]
> try running: `dbus-launch make check-TESTS`

This is not really what dbus-launch is for: if you do this, the temporary D-Bus session bus will persist after the tests have finished.

`dbus-run-session -- make check-TESTS` is a better way to do the same thing. dbus-run-session ensures that the dbus-daemon terminates after the tests finish.
